if OPERATING_SYSTEM==*LINUX goto WEHATELINUX
if OPERATING_SYSTEM==LINUX goto WEHATELINUX
if OPERATING_SYSTEM==WINDOWS or MACOS else goto WELOVEYOU

@WEHATELINUX
GAME::SHOWMESSAGE="Your computer is blocking VAC....."

@WELOVEYOU
GAME::DO_NOTHING
